import random

for i in range(1, 100):
    print(random.uniform(0.125, 1))

# https://www.99acres.com/search/property/buy/delhi?city=1075722&keyword=Delhi&preference=S&area_unit=1&res_com=R
# https://www.99acres.com/property-in-delhi-ffid-page-3
# https://www.99acres.com/property-in-delhi-ffid-page-4
# https://www.99acres.com/property-in-delhi-ffid-page-5
# https://www.99acres.com/property-in-delhi-ffid-page-6
# https://www.99acres.com/property-in-delhi-ffid-page-7
# https://www.99acres.com/property-in-delhi-ffid-page-8
# https://www.99acres.com/property-in-delhi-ffid-page-9
# https://www.99acres.com/property-in-delhi-ffid-page-10
# https://www.99acres.com/property-in-delhi-ffid-page-11
# https://www.99acres.com/property-in-delhi-ffid-page-13
# https://www.99acres.com/property-in-delhi-ffid-page-14
# https://www.99acres.com/property-in-delhi-ffid-page-15
# https://www.99acres.com/property-in-delhi-ffid-page-16
# https://www.99acres.com/property-in-delhi-ffid-page-17
# https://www.99acres.com/property-in-delhi-ffid-page-18
# https://www.99acres.com/property-in-delhi-ffid-page-19
# https://www.99acres.com/property-in-delhi-ffid-page-20
# https://www.99acres.com/property-in-delhi-ffid-page-21
# https://www.99acres.com/property-in-delhi-ffid-page-23
# https://www.99acres.com/property-in-delhi-ffid-page-24
# https://www.99acres.com/property-in-delhi-ffid-page-25
# https://www.99acres.com/property-in-delhi-ffid-page-26
# https://www.99acres.com/property-in-delhi-ffid-page-27
# https://www.99acres.com/property-in-delhi-ffid-page-28
# https://www.99acres.com/property-in-delhi-ffid-page-29
# https://www.99acres.com/property-in-delhi-ffid-page-30
# https://www.99acres.com/property-in-delhi-ffid-page-31
# https://www.99acres.com/property-in-delhi-ffid-page-33
# https://www.99acres.com/property-in-delhi-ffid-page-34
# https://www.99acres.com/property-in-delhi-ffid-page-35
# https://www.99acres.com/property-in-delhi-ffid-page-36
# https://www.99acres.com/property-in-delhi-ffid-page-37
# https://www.99acres.com/property-in-delhi-ffid-page-38
# https://www.99acres.com/property-in-delhi-ffid-page-39
# https://www.99acres.com/property-in-delhi-ffid-page-40
# https://www.99acres.com/property-in-delhi-ffid-page-41
# https://www.99acres.com/property-in-delhi-ffid-page-43
# https://www.99acres.com/property-in-delhi-ffid-page-44
# https://www.99acres.com/property-in-delhi-ffid-page-45
# https://www.99acres.com/property-in-delhi-ffid-page-46
# https://www.99acres.com/property-in-delhi-ffid-page-47
# https://www.99acres.com/property-in-delhi-ffid-page-48
# https://www.99acres.com/property-in-delhi-ffid-page-49
# https://www.99acres.com/property-in-delhi-ffid-page-50
# https://www.99acres.com/property-in-delhi-ffid-page-51
# https://www.99acres.com/property-in-delhi-ffid-page-53
# https://www.99acres.com/property-in-delhi-ffid-page-54
# https://www.99acres.com/property-in-delhi-ffid-page-55
# https://www.99acres.com/property-in-delhi-ffid-page-56
# https://www.99acres.com/property-in-delhi-ffid-page-57
# https://www.99acres.com/property-in-delhi-ffid-page-58
# https://www.99acres.com/property-in-delhi-ffid-page-59
# https://www.99acres.com/property-in-delhi-ffid-page-60
# https://www.99acres.com/property-in-delhi-ffid-page-61
# https://www.99acres.com/property-in-delhi-ffid-page-63
# https://www.99acres.com/property-in-delhi-ffid-page-64
# https://www.99acres.com/property-in-delhi-ffid-page-65
# https://www.99acres.com/property-in-delhi-ffid-page-66
# https://www.99acres.com/property-in-delhi-ffid-page-67
# https://www.99acres.com/property-in-delhi-ffid-page-68
# https://www.99acres.com/property-in-delhi-ffid-page-69
# https://www.99acres.com/property-in-delhi-ffid-page-70
# https://www.99acres.com/property-in-delhi-ffid-page-71
# https://www.99acres.com/property-in-delhi-ffid-page-73
# https://www.99acres.com/property-in-delhi-ffid-page-74
# https://www.99acres.com/property-in-delhi-ffid-page-75
# https://www.99acres.com/property-in-delhi-ffid-page-76
# https://www.99acres.com/property-in-delhi-ffid-page-77
# https://www.99acres.com/property-in-delhi-ffid-page-78
# https://www.99acres.com/property-in-delhi-ffid-page-79
# https://www.99acres.com/property-in-delhi-ffid-page-80
# https://www.99acres.com/property-in-delhi-ffid-page-81
# https://www.99acres.com/property-in-delhi-ffid-page-83
# https://www.99acres.com/property-in-delhi-ffid-page-84
# https://www.99acres.com/property-in-delhi-ffid-page-85
# https://www.99acres.com/property-in-delhi-ffid-page-86
# https://www.99acres.com/property-in-delhi-ffid-page-87
# https://www.99acres.com/property-in-delhi-ffid-page-88
# https://www.99acres.com/property-in-delhi-ffid-page-89
# https://www.99acres.com/property-in-delhi-ffid-page-90
# https://www.99acres.com/property-in-delhi-ffid-page-91
# https://www.99acres.com/property-in-delhi-ffid-page-93
# https://www.99acres.com/property-in-delhi-ffid-page-94
# https://www.99acres.com/property-in-delhi-ffid-page-95
# https://www.99acres.com/property-in-delhi-ffid-page-96
# https://www.99acres.com/property-in-delhi-ffid-page-97
# https://www.99acres.com/property-in-delhi-ffid-page-98
# https://www.99acres.com/property-in-delhi-ffid-page-99
# https://www.99acres.com/property-in-delhi-ffid-page-100
# https://www.99acres.com/property-in-delhi-ffid-page-101
# https://www.99acres.com/property-in-delhi-ffid-page-103
# https://www.99acres.com/property-in-delhi-ffid-page-104
# https://www.99acres.com/property-in-delhi-ffid-page-105
# https://www.99acres.com/property-in-delhi-ffid-page-106
# https://www.99acres.com/property-in-delhi-ffid-page-107
# https://www.99acres.com/property-in-delhi-ffid-page-108
# https://www.99acres.com/property-in-delhi-ffid-page-109
# https://www.99acres.com/property-in-delhi-ffid-page-110
# https://www.99acres.com/property-in-delhi-ffid-page-111
# https://www.99acres.com/property-in-delhi-ffid-page-113
# https://www.99acres.com/property-in-delhi-ffid-page-114
# https://www.99acres.com/property-in-delhi-ffid-page-115
# https://www.99acres.com/property-in-delhi-ffid-page-116
# https://www.99acres.com/property-in-delhi-ffid-page-117
# https://www.99acres.com/property-in-delhi-ffid-page-118
# https://www.99acres.com/property-in-delhi-ffid-page-119
# https://www.99acres.com/property-in-delhi-ffid-page-120
# https://www.99acres.com/property-in-delhi-ffid-page-121
# https://www.99acres.com/property-in-delhi-ffid-page-123
# https://www.99acres.com/property-in-delhi-ffid-page-124
# https://www.99acres.com/property-in-delhi-ffid-page-125
# https://www.99acres.com/property-in-delhi-ffid-page-126
# https://www.99acres.com/property-in-delhi-ffid-page-127
# https://www.99acres.com/property-in-delhi-ffid-page-128
# https://www.99acres.com/property-in-delhi-ffid-page-129
# https://www.99acres.com/property-in-delhi-ffid-page-130
# https://www.99acres.com/property-in-delhi-ffid-page-131
# https://www.99acres.com/property-in-delhi-ffid-page-133
# https://www.99acres.com/property-in-delhi-ffid-page-134
# https://www.99acres.com/property-in-delhi-ffid-page-135
# https://www.99acres.com/property-in-delhi-ffid-page-136
# https://www.99acres.com/property-in-delhi-ffid-page-137
# https://www.99acres.com/property-in-delhi-ffid-page-138
# https://www.99acres.com/property-in-delhi-ffid-page-139
# https://www.99acres.com/property-in-delhi-ffid-page-140
# https://www.99acres.com/property-in-delhi-ffid-page-141
# https://www.99acres.com/property-in-delhi-ffid-page-143
# https://www.99acres.com/property-in-delhi-ffid-page-144
# https://www.99acres.com/property-in-delhi-ffid-page-145
# https://www.99acres.com/property-in-delhi-ffid-page-146
# https://www.99acres.com/property-in-delhi-ffid-page-147
# https://www.99acres.com/property-in-delhi-ffid-page-148
# https://www.99acres.com/property-in-delhi-ffid-page-149
# https://www.99acres.com/property-in-delhi-ffid-page-150
# https://www.99acres.com/property-in-delhi-ffid-page-151
# https://www.99acres.com/property-in-delhi-ffid-page-153
# https://www.99acres.com/property-in-delhi-ffid-page-154
# https://www.99acres.com/property-in-delhi-ffid-page-155
# https://www.99acres.com/property-in-delhi-ffid-page-156
# https://www.99acres.com/property-in-delhi-ffid-page-157
# https://www.99acres.com/property-in-delhi-ffid-page-158
# https://www.99acres.com/property-in-delhi-ffid-page-159
# https://www.99acres.com/property-in-delhi-ffid-page-160
# https://www.99acres.com/property-in-delhi-ffid-page-161
# https://www.99acres.com/property-in-delhi-ffid-page-163
# https://www.99acres.com/property-in-delhi-ffid-page-164
# https://www.99acres.com/property-in-delhi-ffid-page-165
# https://www.99acres.com/property-in-delhi-ffid-page-166
# https://www.99acres.com/property-in-delhi-ffid-page-167
# https://www.99acres.com/property-in-delhi-ffid-page-168
# https://www.99acres.com/property-in-delhi-ffid-page-169
# https://www.99acres.com/property-in-delhi-ffid-page-170
# https://www.99acres.com/property-in-delhi-ffid-page-171
# https://www.99acres.com/property-in-delhi-ffid-page-173
# https://www.99acres.com/property-in-delhi-ffid-page-174
# https://www.99acres.com/property-in-delhi-ffid-page-175
# https://www.99acres.com/property-in-delhi-ffid-page-176
# https://www.99acres.com/property-in-delhi-ffid-page-177
# https://www.99acres.com/property-in-delhi-ffid-page-178
# https://www.99acres.com/property-in-delhi-ffid-page-179
# https://www.99acres.com/property-in-delhi-ffid-page-180
# https://www.99acres.com/property-in-delhi-ffid-page-181
# https://www.99acres.com/property-in-delhi-ffid-page-183
# https://www.99acres.com/property-in-delhi-ffid-page-184
# https://www.99acres.com/property-in-delhi-ffid-page-185
# https://www.99acres.com/property-in-delhi-ffid-page-186
# https://www.99acres.com/property-in-delhi-ffid-page-187
# https://www.99acres.com/property-in-delhi-ffid-page-188
# https://www.99acres.com/property-in-delhi-ffid-page-189
# https://www.99acres.com/property-in-delhi-ffid-page-190
# https://www.99acres.com/property-in-delhi-ffid-page-191
# https://www.99acres.com/property-in-delhi-ffid-page-193
# https://www.99acres.com/property-in-delhi-ffid-page-194
# https://www.99acres.com/property-in-delhi-ffid-page-195
# https://www.99acres.com/property-in-delhi-ffid-page-196
# https://www.99acres.com/property-in-delhi-ffid-page-197
# https://www.99acres.com/property-in-delhi-ffid-page-198
# https://www.99acres.com/property-in-delhi-ffid-page-199
# https://www.99acres.com/property-in-delhi-ffid-page-200
# https://www.99acres.com/property-in-delhi-ffid-page-201
# https://www.99acres.com/property-in-delhi-ffid-page-203
# https://www.99acres.com/property-in-delhi-ffid-page-204
# https://www.99acres.com/property-in-delhi-ffid-page-205
# https://www.99acres.com/property-in-delhi-ffid-page-206
# https://www.99acres.com/property-in-delhi-ffid-page-207
# https://www.99acres.com/property-in-delhi-ffid-page-208
# https://www.99acres.com/property-in-delhi-ffid-page-209
# https://www.99acres.com/property-in-delhi-ffid-page-210
# https://www.99acres.com/property-in-delhi-ffid-page-211
# https://www.99acres.com/property-in-delhi-ffid-page-213
# https://www.99acres.com/property-in-delhi-ffid-page-214
# https://www.99acres.com/property-in-delhi-ffid-page-215
# https://www.99acres.com/property-in-delhi-ffid-page-216
# https://www.99acres.com/property-in-delhi-ffid-page-217
# https://www.99acres.com/property-in-delhi-ffid-page-218
# https://www.99acres.com/property-in-delhi-ffid-page-219
# https://www.99acres.com/property-in-delhi-ffid-page-220
# https://www.99acres.com/property-in-delhi-ffid-page-221
# https://www.99acres.com/property-in-delhi-ffid-page-223
# https://www.99acres.com/property-in-delhi-ffid-page-224
# https://www.99acres.com/property-in-delhi-ffid-page-225
# https://www.99acres.com/property-in-delhi-ffid-page-226
# https://www.99acres.com/property-in-delhi-ffid-page-227
# https://www.99acres.com/property-in-delhi-ffid-page-228
# https://www.99acres.com/property-in-delhi-ffid-page-229
# https://www.99acres.com/property-in-delhi-ffid-page-230
# https://www.99acres.com/property-in-delhi-ffid-page-231
# https://www.99acres.com/property-in-delhi-ffid-page-233
# https://www.99acres.com/property-in-delhi-ffid-page-234
# https://www.99acres.com/property-in-delhi-ffid-page-235
# https://www.99acres.com/property-in-delhi-ffid-page-236
# https://www.99acres.com/property-in-delhi-ffid-page-237
# https://www.99acres.com/property-in-delhi-ffid-page-238
# https://www.99acres.com/property-in-delhi-ffid-page-239
# https://www.99acres.com/property-in-delhi-ffid-page-240
# https://www.99acres.com/property-in-delhi-ffid-page-241



